project:
  type: website
  output-dir: docs

website:
  title: "ClubeR"
  favicon: logo-cluber.png
  site-url: https://astuciasnor.github.io/cluber
  repo-url: https://github.com/astuciasnor/cluber
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer: "© 2025 ClubeR - UFPA/Bragança"
  navbar:
    logo: logo-cluber.png
    left:
      - href: index.qmd
        text: Início
      - href: tutoriais.qmd
        text: Tutoriais
      - href: blog.qmd
        text: Blog
      - href: sobre.qmd
        text: Sobre

format:
  html:
    theme: journal
    toc: true
    number-sections: true
    code-copy: true
    code-overflow: wrap

resources:
  - posts





